repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff
        name: lint with ruff
        language: system
        entry: ruff check --fix
        types: [python]
        require_serial: true

      - id: ruff-format
        name: format with ruff
        language: system
        entry: ruff format
        types: [python]
        require_serial: true

      - id: spotlessApply
        name: format with spotless
        language: system
        entry: bash -c 'cd forge && gradle :spotlessApply'
        pass_filenames: false
        types: [java]

      - id: pyright
        name: type check with pyright
        language: system
        entry: pyright
        types: [python]
        require_serial: true
