repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff
        name: lint with ruff
        language: system
        entry: ruff check
        types: [python]
        require_serial: true

      - id: ruff-format
        name: format with ruff
        language: system
        entry: ruff format
        types: [python]
        require_serial: true

      - id: spotlessApply
        name: format with spotless
        language: system
        entry: bash -c 'cd forge && gradle :spotlessApply'
        pass_filenames: false
        types: [java]

      - id: pyright
        name: type check with pyright
        language: system
        entry: pyright
        types: [python]
        require_serial: true


#  # Java hooks
#  - repo: https://github.com/gherynos/pre-commit-java
#    rev: v0.6.17
#    hooks:
#      - id: pmd
#        files: forge/.*\.java$
#      - id: cpd
#        files: forge/.*\.java$
#      - id: checkstyle
#        files: forge/.*\.java$
