[workspace]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64"]

[dependencies]
pyyaml = "*"
dacite = "*"
gradle = "<9.0.0"
gymnasium = "*"
numpy = "*"
openjdk = "21.*"
pyright = "*"
pytorch = "*"
scipy = "*"
tensorboard = "*"
torchvision = "*"
tqdm = "*"
nodejs = ">=18"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-mock = "*"
ruff = "*"
types-PyYAML = "*"
matplotlib = "*"

[pypi-dependencies]
mineagent = { path = ".", editable = true }

[tasks]
mineagent = "python -m mineagent.engine"
gradle-run-client = "cd forge && gradle runClient"
gradle-build = "cd forge && gradle build"
gradle-test = "cd forge && gradle test"
